### ISSUE TITLE
readme中切换的快捷键错误

### ISSUE THREAD

**Issue by Runninginsilence1** [BHznJNs/InputShare#1]
软件启用后使用的是快捷键 <Ctrl>+<Alt>+s切换的，你的b站视频里面演示的是这样
文档和实际使用时有两处错误：
readme文档中：
<Ctrl>+<Shift>+s：在您的电脑和 Android 设备间切换控制 <Ctrl>+<Shift>+q：退出程序

实际使用时左上角是 <Shift>+<Alt>+s

**Comment by BHznJNs** [comment]
@Runninginsilence1 那应该是没错的呀，`ctrl` + `shift` + s 切换控制，`ctrl` + `shift` + q 关闭程序

**Comment by BHznJNs** [comment]
@Runninginsilence1 你是对的，确实是我标错了。已更正
