### ISSUE TITLE
Add bluetooth connection

### ISSUE THREAD

**Issue by zzabolazza** [BHznJNs/InputShare#3]
connect through bluetooth will be much easier to use, just like what [accross](https://www.acrosscenter.com/) do.

**Comment by BHznJNs** [comment]
Connection via Bluetooth is a complete different way comparing the current implementation, it is no in plan recently.
However, I have been finding a way to simplify the current connection steps, it will be applied in the following release.

**Comment by BHznJNs** [comment]
In the [latest release](https://github.com/BHznJNs/InputShare/releases/tag/0.5.0), i added the ip address memory and port scanning feature, i hope those can help you to simplify the connection.
