### ISSUE TITLE
亲测可以和 `scrcpy` 一起使用

### ISSUE THREAD

**Issue by resticDOG** [BHznJNs/InputShare#5]
windows 下可以在 scrcpy 无线投屏时使用该项目进行键盘共享，但是图形界面使用还是有点不方便，想问下可以提供 `cli` 程序使用吗.

**Comment by BHznJNs** [comment]
scrcpy 不是自带键鼠共享吗，我寻思

**Comment by resticDOG** [comment]
> scrcpy 不是自带键鼠共享吗，我寻思

- 无线连接不能使用键盘
- 有线连接使用键盘的参数`-k`不支持`Windows`平台

**Comment by BHznJNs** [comment]
把输入法切换到英文后，用这个参数：
```
./scrcpy --no-video --no-audio --keyboard=uhid
```

**Comment by resticDOG** [comment]
> 把输入法切换到英文后，用这个参数：
> 
> ```
> ./scrcpy --no-video --no-audio --keyboard=uhid
> ```

scrcpy 更新了最新版 `2.7` 之后确实可以使用，谢谢!
